### ISSUE TITLE
Upgrade to latest joda-time (2.7)

### ISSUE THREAD

**Issue by mauhiz** [JodaOrg/joda-time-hibernate#10]
I'd like to use this project with the latest joda-time. Is there any plan to accept any such contribution?

**Comment by jodastephen** [comment]
It is intended that you declare the dependency on the Joda-Time version of your choice in your own pom.xml. That will override the version pulled in from the hibernate project.

As such, the version in the joda-time-hibernate project represents the *minimum* version needed, and I'm not changing that.

**Comment by mauhiz** [comment]
Hi @jodastephen, this is what I am doing but this led to runtime errors. Maybe I was doing something wrong. Am I right to say that this lib is tested to run fine with joda-time 2.7 ?

**Comment by jodastephen** [comment]
Joda-Time 2.0 and 2.7 are compatible.
