### ISSUE TITLE
PersistentDateTime must implement nullSafeSet

### ISSUE THREAD

**Issue by message** [JodaOrg/joda-time-hibernate#9]
Class 'PersistentDateTime' must either be declared abstract or implement abstract method 'nullSafeSet(PreparedStatement, Object, int, SessionImplementator)' in 'UserType'

```xml
<hibernate.version>4.3.8.Final</hibernate.version>
<jodaTime.version>2.7</jodaTime.version>
<jodaTimeHibernate.version>1.4</jodaTimeHibernate.version>
```

**Comment by jodastephen** [comment]
The Joda-Time-Hibernate project does not work with Hibernate 4. See the [home page](http://www.joda.org/joda-time-hibernate/) for a link to the "usertype" project.

**Comment by message** [comment]
Didn't notice that, may be highlight it with bold somehow?
